&SCENARIO
  Label    = 'MCM32+CAPRAM40'
  WaitBar  = .T.
  Simulation = .T.
  Reduction  = .F.
/END
&FILES
  SysFile  = 'RUN/TESTRUN/MCM+CAPRAM/MCM32_CAPRAM40_full.sys'  
  DataFile = 'RUN/TESTRUN/DAT/MCM32_CAPRAM40_full.dat'
  InitFile = 'RUN/TESTRUN/INI/Urban2.ini'
  RedCtrlFile = 'EXTERNALS/cminor-issa/CONFIG/ISSA/MCM+CAPRAM_2.ctrl'
  DatPolicy  = 'warn'    ! warns when missing species in .dat file
/END
&TIMES
  tBegin      = 0.0d0
  tEnd        = 84600.0d0
/END
&METEO
  pHSet       = .T.          ! Berechne pH Wert zu Beginn
  LWCLevelmax = 2.0d-8       ! minimaler LWC Wert [l/cm3]
  LWCLevelmin = 3.0d-4       ! maximaler LWC Wert [l/cm3]
  Dust        = 0.5d0        ! Zenith Berechnung       (Staub)
  idate       = 010621       ! ---------''---------    (Datum: YYMMDD)
  rlat        = 45.0d0       ! ---------''---------    (Breitengrad)
  rlon        = 0.0d0        ! ---------''---------    (Längengrad)
  Temperature0= 280.0d0
/END
&NUMERICS
  RtolROW  = 1.0d-4
  AtolGas  = 1.0d-5
  AtolAqua = 1.0d-5
  Error_Est = 2
  minStp  = 1.0d-30
  maxStp  = -1.0d0
  ODEsolver = 'METHODS/Rodas3.ros'
/END
&OUTPUT
  NetCdfFile  = 'RUN/TESTRUN/MCM+CAPRAM/MCM32+CAPRAM_issa.nc' ! location and name of NetCDF output file
  StpNetCDF   = -1.0d0              ! save after StpNetCDF seconds, if < 0.0 :  save every timestep
  StpFlux     = -1.0d0
  MatrixPrint = .F.                ! .TRUE. == print matricies , .FALSE. == do not print any matrix
  FluxDataPrint = .T.
/END
